// import Link from 'next/link'
import { getSEOTags } from '@/libs/seo'
import config from '@/config'

// CHATGPT PROMPT TO GENERATE YOUR TERMS & SERVICES — replace with your own data 👇

// 1. Go to https://chat.openai.com/
// 2. Copy paste bellow
// 3. Replace the data with your own (if needed)
// 4. Paste the answer from ChatGPT directly in the <pre> tag below

// You are an excellent lawyer.

// I need your help to write a simple Terms & Services for my website. Here is some context:
// - Website: https://shipfa.st
// - Name: StableCascade
// - Contact information: marc@shipfa.st
// - Description: A JavaScript code boilerplate to help entrepreneurs launch their startups faster
// - Ownership: when buying a package, users can download code to create apps. They own the code but they do not have the right to resell it. They can ask for a full refund within 7 day after the purchase.
// - User data collected: name, email and payment information
// - Non-personal data collection: web cookies
// - Link to privacy-policy: https://shipfa.st/privacy-policy
// - Governing Law: France
// - Updates to the Terms: users will be updated by email

// Please write a simple Terms & Services for my site. Add the current date. Do not add or explain your reasoning. Answer:

export async function generateMetadata() {
  return getSEOTags({
    title: `Terms and Conditions | ${config.appName}`,
    canonicalUrlRelative: `/terms-of-service`,
  })
}

const TOS = () => {
  return (
    <main className='max-w-xl pt-12 mx-auto'>
      <div className='p-10'>
        {/* <Link href='/' className='btn btn-ghost'>
          <svg
            xmlns='http://www.w3.org/2000/svg'
            viewBox='0 0 20 20'
            fill='currentColor'
            className='w-5 h-5'
          >
            <path
              fillRule='evenodd'
              d='M15 10a.75.75 0 01-.75.75H7.612l2.158 1.96a.75.75 0 11-1.04 1.08l-3.5-3.25a.75.75 0 010-1.08l3.5-3.25a.75.75 0 111.04 1.08L7.612 9.25h6.638A.75.75 0 0115 10z'
              clipRule='evenodd'
            />
          </svg>
          Back
        </Link> */}
        <h1 className='pb-6 text-3xl'>
          Terms and Conditions for {config.appName}
        </h1>

        <pre
          className='leading-relaxed whitespace-pre-wrap'
          style={{ fontFamily: 'sans-serif' }}
        >
          {`Last Updated: 2024-02-21

Welcome to StableCascade.net!

These Terms of Service ("Terms") govern your use of the StableCascade website at https://stablecascade.net ("Website") and the services provided by StableCascade. By using our Website and services, you agree to these Terms.

1. Service Description

StableCascade provides text-to-image services. Users can input text, which our system will generate image.

2. Usage Policy

Users must not upload text containing illegal, infringing, offensive, or inappropriate content.

The services of StableCascade must not be used for any illegal purposes.

Users are responsible for the legality and correctness of their uploaded content.

3. Intellectual Property

StableCascade owns the intellectual property rights to its services and related software.

The voice content generated by users belongs to the users, but users agree to allow StableCascade to use this content in providing services.

4. Disclaimer

StableCascade is not responsible for the accuracy, legality, or quality of user-uploaded content.

We are not liable for any indirect, incidental, special, consequential, or punitive damages arising from the use or inability to use the service.

5. Privacy Policy

Your privacy is critically important to us. We are committed to protecting your personal information and data.
For more detailed information, please refer to our Privacy Policy.

6. Modifications and Changes

stablecascade.net reserves the right to modify the services and terms of use at any time.

Continued use of the service will be considered acceptance of the modified terms.

Thank you for using stablecascade.net!`}
        </pre>
      </div>
    </main>
  )
}

export default TOS
